#include <unordered_map>
#include <Rocket/Base/Profile.hpp>
#include <Rocket/Window/Input.hpp>

namespace Rocket {

std::string const& GetKeyName(Key key) {
    PROFILE

    static auto _unknown = std::string("Unknown");
    static auto _namemap = std::unordered_map<Key, std::string>{
        { Key::Unknown, "Unknown" },
        { Key::Digit0, "0" },
        { Key::Digit1, "1" },
        { Key::Digit2, "2" },
        { Key::Digit3, "3" },
        { Key::Digit4, "4" },
        { Key::Digit5, "5" },
        { Key::Digit6, "6" },
        { Key::Digit7, "7" },
        { Key::Digit8, "8" },
        { Key::Digit9, "9" },
        { Key::KeyA, "A" },
        { Key::KeyB, "B" },
        { Key::KeyC, "C" },
        { Key::KeyD, "D" },
        { Key::KeyE, "E" },
        { Key::KeyF, "F" },
        { Key::KeyG, "G" },
        { Key::KeyH, "H" },
        { Key::KeyI, "I" },
        { Key::KeyJ, "J" },
        { Key::KeyK, "K" },
        { Key::KeyL, "L" },
        { Key::KeyM, "M" },
        { Key::KeyN, "N" },
        { Key::KeyO, "O" },
        { Key::KeyP, "P" },
        { Key::KeyQ, "Q" },
        { Key::KeyR, "R" },
        { Key::KeyS, "S" },
        { Key::KeyT, "T" },
        { Key::KeyU, "U" },
        { Key::KeyV, "V" },
        { Key::KeyW, "W" },
        { Key::KeyX, "X" },
        { Key::KeyY, "Y" },
        { Key::KeyZ, "Z" },
        { Key::F1, "F1" },
        { Key::F2, "F2" },
        { Key::F3, "F3" },
        { Key::F4, "F4" },
        { Key::F5, "F5" },
        { Key::F6, "F6" },
        { Key::F7, "F7" },
        { Key::F8, "F8" },
        { Key::F9, "F9" },
        { Key::F10, "F10" },
        { Key::F11, "F11" },
        { Key::F12, "F12" },
        { Key::F13, "F13" },
        { Key::F14, "F14" },
        { Key::F15, "F15" },
        { Key::F16, "F16" },
        { Key::F17, "F17" },
        { Key::F18, "F18" },
        { Key::F19, "F19" },
        { Key::F20, "F20" },
        { Key::Alt, "Alt" },
        { Key::ArrowDown, "ArrowDown" },
        { Key::ArrowLeft, "ArrowLeft" },
        { Key::ArrowRight, "ArrowRight" },
        { Key::ArrowUp, "ArrowUp" },
        { Key::Backslash, "\\" },
        { Key::Backspace, "Backspace" },
        { Key::BracketLeft, "[" },
        { Key::BracketRight, "]" },
        { Key::Capslock, "Capslock" },
        { Key::Comma, "," },
        { Key::Control, "Control" },
        { Key::End, "End" },
        { Key::Equal, "=" },
        { Key::Escape, "Escape" },
        { Key::Delete, "Delete" },
        { Key::Function, "Fn" },
        { Key::Backquote, "`" },
        { Key::Help, "Help" },
        { Key::Home, "Home" },
        { Key::Meta, "Meta" },
        { Key::Minus, "-" },
        { Key::Mute, "Mute" },
        { Key::PageDown, "PageDown" },
        { Key::PageUp, "PageUp" },
        { Key::Period, "." },
        { Key::Quote, "'" },
        { Key::Enter, "Enter" },
        { Key::AltRight, "AltRight" },
        { Key::ControlRight, "ControlRight" },
        { Key::ShiftRight, "ShiftRight" },
        { Key::Semicolon, ";" },
        { Key::Shift, "Shift" },
        { Key::Slash, "/" },
        { Key::Space, "Space" },
        { Key::Tab, "Tab" },
        { Key::VolumeDown, "VolumeDown" },
        { Key::VolumeUp, "VolumeUp" },
        { Key::NumpadClear, "NumpadClear" },
        { Key::NumpadDecimal, "NumpadDecimal" },
        { Key::NumpadDivide, "NumpadDivide" },
        { Key::NumpadEnter, "NumpadEnter" },
        { Key::NumpadEqual, "NumpadEqual" },
        { Key::NumpadMinus, "NumpadMinus" },
        { Key::NumpadMultiply, "NumpadMultiply" },
        { Key::NumpadAdd, "NumpadAdd" },
        { Key::Numpad0, "Numpad0" },
        { Key::Numpad1, "Numpad1" },
        { Key::Numpad2, "Numpad2" },
        { Key::Numpad3, "Numpad3" },
        { Key::Numpad4, "Numpad4" },
        { Key::Numpad5, "Numpad5" },
        { Key::Numpad6, "Numpad6" },
        { Key::Numpad7, "Numpad7" },
        { Key::Numpad8, "Numpad8" },
        { Key::Numpad9, "Numpad9" }
    };

    auto it = _namemap.find(key);
    if (it != _namemap.end()) {
        return it->second;
    } else {
        return _unknown;
    }
}

} /* namespace Rocket */